feat(Task-1A)
SamuFigueirido/Practices2019 pull request #1
Opened 2019-04-10 12:40 UTC by SamuFigueirido

2019-04-10 14:37 UTC, eloydotco requested changes

2019-04-10 14:37 UTC, gbtec-ext-eloycastelo commented on Ejercicio1/index-START.html
> +    //console.log(e.keyCode);
Please, remove commented lines of code, unless are necessary for future development (if the case, you have to write a comment explaining the reason) :)

2019-04-10 14:37 UTC, gbtec-ext-eloycastelo commented on Ejercicio1/index-START.html
> +    if(!audio)return;
We try to avoid one-line if statement, because it's more readable the normal way (we have to think on the person who come next :) )
```
if (something) {
...
}
```

Additionally, it would be better to make this check before the previous statement, because if the audio is null, we have spent time with the querySelector.

2019-04-10 14:37 UTC, gbtec-ext-eloycastelo commented on Ejercicio1/index-START.html
> +    if(e.propertyName !== 'transform')return;
Same as before, try to avoid one-line if statements

2019-04-10 14:58 UTC, gbtec-ext-jorgevillar requested changes

2019-04-10 14:58 UTC, gbtec-ext-jorgevillar commented on Ejercicio1/index-START.html
> +  window.addEventListener('keydown', function(e){
Make use of lambda expresions `(e) => { ... }` always you can

2019-04-10 14:58 UTC, gbtec-ext-jorgevillar commented on Ejercicio1/index-START.html
> +    const audio=document.querySelector(`audio[data-key="${e.keyCode}"]`);
place a whitespace before and after an '=' on assignements like `const audio = blablabla`

2019-04-10 14:58 UTC, gbtec-ext-jorgevillar commented on Ejercicio1/index-START.html
> +    if(e.propertyName !== 'transform')return;
Same as Eloy and place a whitespace afte the 'if' and after the ') like this: `if (....) {`

2019-04-11 06:55 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-11 11:00 UTC, eloydotco requested changes

2019-04-11 11:00 UTC, gbtec-ext-eloycastelo commented on Ejercicio1/index-START.html
> +    if (!audio) {
Here `audio` always will be undefined because it is declared later, you have to put it below.

2019-04-11 11:43 UTC, SamuFigueirido commented on Ejercicio1/index-START.html
> +    if (!audio) {
Ok, I changed it, `audio` is declared at the beginning, before the `if`

2019-04-11 14:45 UTC, eloydotco approved these changes
You have to be carefully with the files you are "uploading", try to include on the PR only the files related with the feature/fix you are working on.

2019-04-11 14:49 UTC, merged