feat(Task-13): As an user, I wan't a Drum Kit on IE
SamuFigueirido/Practices2019 pull request #14
Opened 2019-04-12 14:27 UTC by SamuFigueirido

2019-04-12 14:39 UTC, eloydotco requested changes

2019-04-12 14:39 UTC, gbtec-ext-eloycastelo commented on Exercise1IE/index-START.html
> +      if (!audio) {
You should check if exist before try to use it

2019-04-15 07:09 UTC, gbtec-ext-jorgevillar requested changes

2019-04-15 07:09 UTC, gbtec-ext-jorgevillar commented on Exercise1IE/index-START.html
> +      if(audio != null) {
Use the triple equal ('===' or '!==') unless you are really sure you need the double equal.
Plave a whitespace between 'if' and the '('

2019-04-15 07:31 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-17 09:28 UTC, eloydotco approved these changes

2019-04-17 09:28 UTC, gbtec-ext-eloycastelo commented on Exercise1IE/index-START.html
> +      if (!audio) {
now I think this if statement is not necessary, right??

2019-04-22 10:23 UTC, merged