feat(Task-17): As a Developer, I want a Flex Panels Image Gallery with more readable styles
SamuFigueirido/Practices2019 pull request #16
Opened 2019-04-16 08:40 UTC by SamuFigueirido

2019-04-16 08:50 UTC, eloydotco approved these changes

2019-04-16 08:50 UTC, gbtec-ext-eloycastelo commented on Exercise5IE/style.scss
> +.panel {
You can "group" styles, imo it's more intuitive when the styles has tree structure like
```
.panels {
  <panels styles>
  ...
  .panel {
    <panel styles>
    ...
  }
}
```
this way also increase the specificity

2019-04-16 10:58 UTC, gbtec-ext-jorgevillar requested changes

2019-04-16 10:58 UTC, gbtec-ext-jorgevillar commented on Exercise5IE/mixins.scss
> +  }
The identation isn't right in this file

2019-04-22 13:47 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-22 13:49 UTC, merged