feat(Task-22): As Nick Fury, I want a heroes register screen
SamuFigueirido/Practices2019 pull request #18
Opened 2019-04-22 12:39 UTC by SamuFigueirido

2019-04-22 13:39 UTC, eloydotco approved these changes

2019-04-22 14:00 UTC, gbtec-ext-jorgevillar reviewed
The scroll bar only should be shown for the form part

2019-04-22 14:00 UTC, gbtec-ext-jorgevillar commented on Heroes_Register_Screen/index.html
> +            <button class="btn-primary dropdown-toggle" type="button" data-toggle="dropdown">City
The cities aren't shown when I press the button

2019-04-24 10:47 UTC, gbtec-ext-jorgevillar requested changes
In mobile mode I still have a scroll bar in the form

2019-04-26 06:41 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-26 06:46 UTC, merged