Feat(Task-8): As a User, I want a Custom HTML5 Video Player
SamuFigueirido/Practices2019 pull request #19
Opened 2019-04-23 15:24 UTC by SamuFigueirido

2019-04-24 06:37 UTC, eloydotco approved these changes

2019-04-24 06:37 UTC, gbtec-ext-eloycastelo commented on Exercise11/scripts.js
> +    console.log(this.dataset.skip);
Please, remove this log

2019-04-24 10:35 UTC, gbtec-ext-jorgevillar requested changes

2019-04-24 10:35 UTC, gbtec-ext-jorgevillar commented on Exercise11/scripts.js
> +let mousedown = false;
I would put this variable at the beginning where you define the consts

2019-04-24 10:35 UTC, gbtec-ext-jorgevillar commented on Exercise11/style.css
> +}
This class has the same styles as the one above, please, join them

2019-04-26 06:38 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-26 06:38 UTC, gbtec-ext-jorgevillar commented on Exercise11/style.css
> +.player:-webkit-full-screen, .player:fullscreen {
This is only a personal preference:
I prefer to put each selector in different line:
.player:fullscreen, 
.player:-webkit-full-screen {
If you have a lot of the or they are longer I think it's more readable this way

2019-04-26 06:47 UTC, merged