feat(Task-1B): As a Project Manager, already done exercises uploaded to the git repository
SamuFigueirido/Practices2019 pull request #2
Opened 2019-04-10 12:44 UTC by SamuFigueirido

2019-04-10 14:38 UTC, eloydotco approved these changes

2019-04-10 14:38 UTC, gbtec-ext-eloycastelo commented on Ejercicio2/index-START.html
> +
Please, remove this extra empty spacing

2019-04-10 14:38 UTC, gbtec-ext-eloycastelo commented on Ejercicio2/index-START.html
> +    const hourHand=document.querySelector('.hour-hand');
this case is very simple, but in the real world we should check all variable before using it, and/or provide a fallback value, for example:
```
const hoursHand = document.querySelector('.hour-hand') || 0;
```
This way hoursHand always will have a valid number value, if you don't know about `||` ,`&&` and falsy/truthy values, please investigate them beucase they are really useful

2019-04-10 15:20 UTC, gbtec-ext-jorgevillar requested changes

2019-04-10 15:20 UTC, gbtec-ext-jorgevillar commented on Ejercicio2/index-START.html
> +    const hourHand=document.querySelector('.hour-hand') || 0;
As Eloy said, place whitespace before and after the '='

2019-04-10 15:20 UTC, gbtec-ext-jorgevillar commented on Ejercicio2/index-START.html
> +    function setDate(){
whe usually place a whitespace between  '()' and '{'

2019-04-11 06:53 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-11 06:55 UTC, merged