Feat(Task-15): As an user, I wan't a Slide in on Scroll on IE
SamuFigueirido/Practices2019 pull request #21
Opened 2019-04-24 15:54 UTC by SamuFigueirido

2019-04-25 06:44 UTC, eloydotco requested changes

2019-04-25 06:44 UTC, gbtec-ext-eloycastelo commented on Exercise13IE/index-FINISHED.html
> +        var later = function () {
Please, use const or let here and above

2019-04-25 06:44 UTC, gbtec-ext-eloycastelo commented on Exercise13IE/index-FINISHED.html
> +        var callNow = immediate && !timeout;
Same as before

2019-04-26 06:43 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-26 10:29 UTC, eloydotco approved these changes

2019-04-26 10:30 UTC, merged