feat(Task-1C): As a Project Manager, already done exercises uploaded to the git repository
SamuFigueirido/Practices2019 pull request #3
Opened 2019-04-10 12:47 UTC by SamuFigueirido

2019-04-10 14:40 UTC, eloydotco requested changes

2019-04-10 14:40 UTC, gbtec-ext-eloycastelo commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('mousemove', handleUpdate));
Please avoid to iterate something twice, you can do it with just one forEach :)

2019-04-10 14:40 UTC, gbtec-ext-eloycastelo commented on Ejercicio3/index-START.html
> +      //console.log(this.dataset);
Please, remove commented lines of code :)

2019-04-10 15:27 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-10 15:27 UTC, gbtec-ext-jorgevillar commented on Ejercicio3/index-START.html
> +</html>
Change the target branch of this PR to 'development' and check it on your other branches

2019-04-10 15:27 UTC, gbtec-ext-jorgevillar commented on Ejercicio3/index-START.html
> +    function handleUpdate(){
Place a whitespace between '()' and '{'

2019-04-11 06:46 UTC, eloydotco requested changes

2019-04-11 06:46 UTC, gbtec-ext-eloycastelo commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
Did you test this arrow functions?? works?? 😕

2019-04-11 06:49 UTC, SamuFigueirido commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
Yes, it works

2019-04-11 07:26 UTC, gbtec-ext-eloycastelo commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
Please, check it again, maybe this helps you :)
We can take a look together if you want 👍 

```
  <script>
    const inputs = document.querySelectorAll('.controls input');
    function handleUpdate(ev) {
      console.log(ev.type);
      const suffix = this.dataset.sizing || '';
      document.documentElement.style.setProperty(`--${this.name}`,this.value + suffix);
    }

    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
  </script>
```

2019-04-11 07:40 UTC, SamuFigueirido commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
Ok, sorry about that, I have already changed the code :D

2019-04-11 07:57 UTC, gbtec-ext-eloycastelo commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
mmm 😕 
did you check if the mousemove event type appears on the devtools console?? :D

2019-04-11 08:02 UTC, SamuFigueirido commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
Yes, sorry, i'm silly
I checked and I found the error. I think it is ok now

2019-04-11 08:07 UTC, eloydotco approved these changes

2019-04-11 08:08 UTC, merged

2019-04-11 08:08 UTC, gbtec-ext-eloycastelo commented on Ejercicio3/index-START.html
> +    inputs.forEach(input => input.addEventListener('change', handleUpdate), input => input.addEventListener('mousemove', handleUpdate));
great 👍  don't worry, this happens all the time :)