feat(Task-1D): As a Project Manager, already done exercises uploaded to the git repository
SamuFigueirido/Practices2019 pull request #4
Opened 2019-04-10 12:50 UTC by SamuFigueirido

2019-04-10 14:44 UTC, eloydotco approved these changes
Looks good in general, but the code formatting looks a little bit strange for me :)
for example, there is no spacing on assigment statements like `const fifteen=inventors...`
is this intended? do you use a code formatter?

2019-04-10 15:29 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-10 15:29 UTC, gbtec-ext-jorgevillar commented on Ejercicio4/index-START.html
> +<!DOCTYPE html>
Change the target branch of this PR to 'development' and check it on your other branches

2019-04-10 15:29 UTC, gbtec-ext-jorgevillar commented on Ejercicio4/index-START.html
> +    const fifteen=inventors.filter(function(inventor){
Use a Lambda here

2019-04-10 15:29 UTC, gbtec-ext-jorgevillar commented on Ejercicio4/index-START.html
> +    const fullNames=inventors.map(inventor => inventor.first +' '+ inventor.last);
place whitespace before and after the '=' in all the JS code

2019-04-10 15:30 UTC, gbtec-ext-jorgevillar requested changes
I wanted to reget the changes

2019-04-11 06:52 UTC, gbtec-ext-jorgevillar approved these changes

2019-04-11 06:55 UTC, merged